- name: Get SA Token playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
     
          
    - name: Debug information
      ansible.builtin.debug:
        msg: "ServiceAccount in namespace '{{ namespace }}' with name '{{ sa_name }}‘"

    - name: Creating token for SA '{{ sa_name }}‘
      ansible.builtin.command: oc create token -n {{ namespace }} {{ sa_name }}
      register: output

    - name: Show SA token
      ansible.builtin.debug:
        var: output.stdout
      when: output.failed == false
 
